### ISSUE TITLE
Add MAINTAINERS.md file

### ISSUE THREAD

**Issue by joewxboy** [open-horizon-services/web-helloworld-go#5]
Please duplicate the file in https://raw.githubusercontent.com/open-horizon-services/web-helloworld-cpp/ac403917069c896f685a317f4ca6b503694f5187/MAINTAINERS.md in this repo.

**Comment by CKacper** [comment]
Hello You can assign me :)

**Comment by joewxboy** [comment]
You got it, @CKacper .  Please review the [Contribution documentation](https://open-horizon.github.io/common-requests/contribute.html) before your first commit.  The "Attestation" section is most often missed, causing re-work. :)

**Comment by CKacper** [comment]
@joewxboy I don't know what I am missing. I think i did everything as in attestation section but still DCO check is failed, any tips?
